### ISSUE TITLE
[Enhancement] Add FreeBSD support

### ISSUE THREAD

**Issue by lsalvadore** [ProtonVPN/linux-cli#111]
Most of Linux software can easily be ported to FreeBSD. Since protonvpn-cli-ng is python based, porting it to FreeBSD should be almost straightforwared. Unfortunately, some Linuxism are present in the code.
An example is "ip route show": on FreeBSD we do not have ip, but we have netstat and I think Linux has it as well. So it is possibile to replace that code with "netstat -r".

I would like to fork the project and try to fix those Linuxisms.

**Comment by Rafficer** [comment]
netstat on Linux has been deprecated and doesn't come preinstalled on many distros anymore, so just replacing `ip route show` with `netstat -r` is not an option.

**Comment by lsalvadore** [comment]
Thanks for your help. I will start working immediately and then let you know when it is ready through a PR.

**Comment by lsalvadore** [comment]
I am sorry, but I lost interest in this work. I close the issue so no one thinks that someone is actually working on it.
