### ISSUE TITLE
Most recent release returns exit code 1 for successful commands

### ISSUE THREAD

**Issue by skeydan** [ProtonVPN/linux-cli#12]
Hi,

I've noticed that after upgrading to ProtonVPN CLI v3.7.0 (protonvpn-nm-lib v3.3.0; proton-client v0.5.1), commands like `protonvpn-cli ks --on`, `protonvpn-cli status` etc. have exit code 1, which breaks syntax like 

`protonvpn-cli ks --on && protonvpn-cli r && protonvpn-cli status`

Is there a chance that the previous behavior will be restored? Thanks!

**Comment by calexandru2018** [comment]
Hey @skeydan 

Thank you for your input. It's definitely something that can be improved, we'll fix this 👍🏻

**Comment by skeydan** [comment]
Great!

**Comment by trstickland** [comment]
@calexandru2018  is the blocked by issue [#14](https://github.com/ProtonVPN/linux-cli/issues/14)?

thanks

**Comment by calexandru2018** [comment]
Hey @trstickland, not really. The fix has been deployed to beta/unstable repo. Should he coming to stable soon.

**Comment by calexandru2018** [comment]
Hey all, this should be now fixed. Please close the ticket.

**Comment by skeydan** [comment]
It is! Thanks!
