### ISSUE TITLE
Python deprecated function warning in Fedora

### ISSUE THREAD

**Issue by homeisfar** [ProtonVPN/linux-cli#14]
I just installed the 1.0.1 rpm with the latest ProtonVPN CLI on an up-to-date Fedora 34. Any time I invoke protonvpn-cli (login, connection) I am warned about this deprecated function.

```
/usr/lib/python3.9/site-packages/secretstorage/dhcrypto.py:16: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3.9/site-packages/secretstorage/util.py:25: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
```

Aside from that it appears to function normally with a UDP connection. That said, seeing the message "Successfully connected to ProtonVPN" with an exit code 1 is very confusing to see, as mentioned in #12.

**Comment by calexandru2018** [comment]
Hey @homeisfar 

This behavior is due to sub-package dependencies and we can't do much about it unfortunately, until either the package maintainers release a new update.
