### ISSUE TITLE
change pgrep --exact to pgrep -x

### ISSUE THREAD

**Issue by felixhopfauf** [ProtonVPN/linux-cli#144]
Hello,

is it possible for you to change pgrep --exact on line 191 to pgrep -x to make it compatible with alpine linux ? I am not really sure about the difference but it seems to work on alpine

kind regards

**Comment by Rafficer** [comment]
[Well...](https://github.com/ProtonVPN/protonvpn-cli-ng/pull/85#issuecomment-571498429)

Is alpine using an old version of procps?

**Comment by felixhopfauf** [comment]
It is useing procps-3.3.16-r0 which seems to be the latest

**Comment by Rafficer** [comment]
Weird... Guess I'll change it to `-x` then...

**Comment by felixhopfauf** [comment]
Thanks a lot :)
