### ISSUE TITLE
[BUG] Kill switch doesn't work

### ISSUE THREAD

**Issue by liamaharon** [ProtonVPN/linux-cli#150]
**Describe the bug**
`protonvpn status` shows kill switch is active and VPN is disconnected
```
liam@sleeper:~$ protonvpn status
Status:     Disconnected
[!] Kill Switch is currently active.
```

 but I still have internet access. I am writing this issue with no VPN connection, even though kill switch is active.

**To Reproduce**
1. Enable kill switch
2. Disconnect from VPN
3. Use internet 

**Expected behavior**
All traffic should be blocked when the kill switch is enabled and there is no vpn connection

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - Python Version: 3.7.5
 - ProtonVPN-CLI Version: 2.2.2

**Comment by liamaharon** [comment]
hmm, I understand from the docs more carefully that this is intended behaviour. I guess this should actually be a feature request, my mistake.

a common use for a kill switch is to prevent any unintentional non-VPN traffic, for example when the user forgets to connect to the vpn. maybe there should be an option for an always-on kill switch?

**Comment by calexandru2018** [comment]
Kill-switch kicks in only if the the VPN process is running, it then blocks all non-encrypted data transmission. If you disconnect from the VPN that is expected behavior as you have stated.

**Comment by binary-signal** [comment]
I think this specific issue can be translated to as a "nice to have future in protonvpn cli", for users that have more security concerns than the rest of us.

**Comment by Rafficer** [comment]
Please read through #157, we've had a more extensive discussion there. If this clears things up, please close this issue as well. 🙂
