### ISSUE TITLE
[Enhancement] Wireguard

### ISSUE THREAD

**Issue by f35f0ef9d0e827dae86552d3899f78fc** [ProtonVPN/linux-cli#156]
I know that this tool is completely based on controlling OpenVPN, so maybe this isn't the best place to ask: Is ProtonVPN doing any R&D on offering Wireguard as a VPN option?

**Comment by Rafficer** [comment]
Yes, it's coming eventually. But as this is not an issue of the CLI (yet) I'll close it.

**Comment by cantalupo555** [comment]
> Yes, it's coming eventually. But as this is not an issue of the CLI (yet) I'll close it.
 
We want Wireguard :heart:

**Comment by agates** [comment]
Is this an issue of the CLI now? :)

**Comment by dlecan** [comment]
Supported or not ?
