### ISSUE TITLE
VPN decreases internet speed 

### ISSUE THREAD

**Issue by howsendrag** [ProtonVPN/linux-cli#159]
Hi. I use proton vpn both in my PC and laptop. The problem is my laptop is windows and always proton vpn connects fast and the internet speed is good, but in my PC (linux - ubuntu) always I connect to vpn with difficulty and internet speed is not acceptable.

**Comment by Rafficer** [comment]
The Client can't help there. Please try this guide or contact support.

https://protonvpn.com/support/increase-vpn-speeds/

https://protonvpn.com/support-form
