### ISSUE TITLE
not bug! wrong link in ubuntu 18.04, ProtonVPN-CLI v2.2.6

### ISSUE THREAD

**Issue by aliskinr** [ProtonVPN/linux-cli#16]
https://github.com/ProtonVPN/linux-cli/blob/master/USAGE.md#updating-protonvpn-cli

I did not take a screenshot.
When launched, the command line showed information about the new version **with a link** to the GIT. Bad link (?)

**Comment by aliskinr** [comment]
oh, its the seme to https://github.com/ProtonVPN/linux-cli/issues/5

**Comment by calexandru2018** [comment]
Hey, I'm closing this issue as the new updated has fixed this. 

Thank you for contribution!
