### ISSUE TITLE
[BUG] Can't connect using systemd service

### ISSUE THREAD

**Issue by marv69** [ProtonVPN/linux-cli#160]
**Describe the bug**
When I follow these instructions:
[Auto connect on boot instructions for cli](https://github.com/ProtonVPN/linux-cli/blob/master/USAGE.md#auto-connect-on-boot)

I don't get a working service. Instead I get the error that the module 'docopt' couldn't be imported.

**To Reproduce**
1. Follow steps mentioned here: 
[Auto connect on boot instructions for cli](https://github.com/ProtonVPN/linux-cli/blob/master/USAGE.md#auto-connect-on-boot)
2. Use this command: 
`sudo systemctl start protonvpn-autoconnect.service`
3. Instead of starting the service it gives me this error:
`protonvpn[2534]: ModuleNotFoundError: No module named 'docopt'`

**Expected behavior**
Service should start instead of giving error

**Error Messages/Program Output/Log Messages (~/.pvpn-cli/pvpn-cli.log)**
May 02 22:39:51 myserver systemd[1]: Starting ProtonVPN-CLI auto-connect...

May 02 22:39:51 myserver protonvpn[2534]: Traceback (most recent call last):

May 02 22:39:51 myserver protonvpn[2534]:   File "/usr/local/bin/protonvpn", line 7, in <module>

May 02 22:39:51 myserver protonvpn[2534]:     from protonvpn_cli.cli import main

May 02 22:39:51 myserver protonvpn[2534]:   File "/usr/local/lib/python3.6/dist-packages/protonvpn_cli/cli.py", line 55, in <module>

May 02 22:39:51 myserver protonvpn[2534]:     from docopt import docopt

May 02 22:39:51 myserver protonvpn[2534]: ModuleNotFoundError: No module named 'docopt'

May 02 22:39:51 myserver systemd[1]: protonvpn-autoconnect.service: Control process exited, code=exited status=1

May 02 22:39:51 myserver systemd[1]: protonvpn-autoconnect.service: Failed with result 'exit-code'.

May 02 22:39:51 myserver systemd[1]: Failed to start ProtonVPN-CLI auto-connect.

**Desktop (please complete the following information):**
 - OS: Ubuntu server 18.04 LTS
 - Python Version: 3.6.9
 - ProtonVPN-CLI Version: v2.2.2

**Additional context**
Contents of my service file protonvpn-autoconnect.service (same as manual):
[Unit]
Description=ProtonVPN-CLI auto-connect
Wants=network-online.target

[Service]
Type=forking
ExecStart=/usr/local/bin/protonvpn connect
Environment=PVPN_WAIT=300
Environment=PVPN_DEBUG=1
Environment=SUDO_USER={my_username}

[Install]
WantedBy=multi-user.target

**Comment by marv69** [comment]
It's also worth mentioning that this one didn't work for me:
`sudo systemctl daemon-reload .`

It gives me this error: 
`Too many arguments.`

So I executed this, which seems to work:
`sudo systemctl daemon-reload`

**Comment by Rafficer** [comment]
Seems like you didn't install the CLI for system python but either in user context or a virtual environment.

**Comment by marv69** [comment]
I used these commands to install the tool yesterday, seems they had sudo.
Am I overlooking something?
`
 1728  sudo apt install -y openvpn dialog python3-pip python3-setuptools
 1729  sudo pip3 install protonvpn-cli
 1730  sudo protonvpn init
`

**Comment by marv69** [comment]
Thanks man, I went with:
`sudo su`

`pip3 install protonvpn-cli`

And this made the problem go away. 
Thank you very much for your help!
