### ISSUE TITLE
[BUG] Cannot connect - timeout (fedora 31)

### ISSUE THREAD

**Issue by qortex** [ProtonVPN/linux-cli#161]
Invariably, I get:

```sh
$ sudo protonvpn c --cc FR
Connecting to FR#36 via UDP...
Connection timed out after 45 Seconds
```

**Error Messages/Program Output/Log Messages (~/.pvpn-cli/pvpn-cli.log)**

`~/.pvpn-cli/pvpn-cli.log`:
```sh
2020-05-04 14:22:36,463 — protonvpn-cli — DEBUG — get_ip_info:143 — Getting IP Information
2020-05-04 14:22:36,463 — protonvpn-cli — DEBUG — call_api:36 — Initiating API Call: https://api.protonvpn.ch/vpn/location
2020-05-04 14:22:36,575 — protonvpn-cli — DEBUG — call_api:65 — Successful json response
2020-05-04 14:22:36,581 — protonvpn-cli — DEBUG — openvpn_connect:482 — OpenVPN process started
2020-05-04 14:23:21,610 — protonvpn-cli — DEBUG — openvpn_connect:530 — Connection timed out after 45 Seconds
```

```sh
...
Mon May  4 14:22:42 2020 GDG6: remote_host_ipv6=n/a
Mon May  4 14:22:42 2020 ROUTE6: default_gateway=UNDEF
Mon May  4 14:22:42 2020 TUN/TAP device proton0 opened
Mon May  4 14:22:42 2020 TUN/TAP TX queue length set to 100
Mon May  4 14:22:42 2020 /sbin/ip link set dev proton0 up mtu 1500
Mon May  4 14:22:42 2020 /sbin/ip addr add dev proton0 10.50.0.10/16 broadcast 10.50.255.255
Mon May  4 14:22:42 2020 /sbin/ip -6 addr add xxxxxx08/112 dev proton0
RTNETLINK answers: Permission denied
Mon May  4 14:22:42 2020 Linux ip -6 addr add failed: external program exited with error status: 2
Mon May  4 14:22:42 2020 Exiting due to fatal error
```

**Desktop (please complete the following information):**
 - OS: Fedora 31
 - Python Version: 3.7.7
 - ProtonVPN-CLI Version: 2.2.2

**Additional context**
Used to work a while ago.

**Comment by qortex** [comment]
Turns out I had IPv6 disabled.

Enabling IPv6 fixes the issue.

It would be nice to have a proper error message (if this is intended behavior?)

**Comment by Rafficer** [comment]
In your case it's OpenVPN failing entirely, which the CLI can't help with.

**Comment by qortex** [comment]
The CLI can certainly help by outputting a more friendly error message than the false message "time out". The issue is not a timeout.

At least give the log files to look for would be a good help and save time.

**Comment by Rafficer** [comment]
True, but there can be a thousand different errors why something goes wrong. The timeout is just the default if the error isn't known.

And while this might be fine for you, getting more technical and giving users the output of a log file to search for the error isn't great for everyone.

**Comment by qortex** [comment]
Sure I understand it's the default message, but i'm skeptical about this UX: as a non-tech user you get an error message that is unrelated to the issue you are having. So you might check your connection for timeout, wait & retry later, ...

As a tech user, well, you end up on git as I did and find the log files to look for by chance.

The error message should at least point to some way to diagnose / report the problem and get help IMO.

In any case, the message should read "failed" instead of "timed out" IMO.

**Comment by Rafficer** [comment]
That I agree with. Timeout may be the wrong wording and could be improved. I'll see that I'll change this.
