### ISSUE TITLE
[!] Error connecting to VPN.  .protonvpn-cli/connection_logs: No such file or directory

### ISSUE THREAD

**Issue by primetimber** [ProtonVPN/linux-cli#171]
Hello
I am having an issue connecting. I have updated the script and checked the credentials. Removed .protonvpn-cli and reinstalled again. But ths didn't work.

I added the "missing file" to the directory and started the client, same error and the connection_logs file I created was removed.

Searched the net, but didn't find anything usefull and decided to bother you. ty for your time.

**Comment by Rafficer** [comment]
Is IPv6 disabled on your system?

Please post the 2 log files in the `~/.pvpn-cli` directory

**Comment by primetimber** [comment]
IPv6 was deactivated on my wireless network connection. Activated it. Reconnected. But the same error occured. 

On my system I have ~/.protonvpn_cli and as far as I can see no log files, but these

> -r--------  1 root      root           1 Mai 16 10:16 .decrease_openvpn_privileges
-r--------  1 root      root         201 Mai 16 10:16 .dialogrc
-rw-r--r--  1 root      root          36 Mai 16 11:23 .ipv6_address
dr--------  2 root      root        4096 Mai 16 10:30 openvpn_cache
-rw-r--r--  1 root      root        4723 Mai 16 11:23 protonvpn_openvpn_config.conf
-r--------  1 root      root          36 Mai 16 10:16 protonvpn_openvpn_credentials
-r--------  1 root      root           2 Mai 16 10:16 protonvpn_tier
-rw-r--r--  1 root      root         230 Mai 16 11:23 .resolv.conf.protonvpn_backup
-rw-r--r--  1 root      root      474001 Mai 16 11:23 .response_cache

**Comment by primetimber** [comment]
sorry wrong button

**Comment by Rafficer** [comment]
You're using the old CLI from https://github.com/ProtonVPN/protonvpn-cli

Please upgrade to this version.
