### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by d762** [ProtonVPN/linux-cli#174]
I get following error:

It looks like there never was a connection.
Please connect with 'protonvpn connect' first.

then when i do sudo protonvpn c -f

There is already a VPN connection running.
Terminating previous connection...
Connecting to NL-FREE#2 via UDP...
Connected!

**To Reproduce**
Setup systemctl to run protonvpn as root as follows:

[Unit]
Description=ProtonVPN
After=syslog.target network-online.target
Wants=network-online.target

[Service]
Type=forking
ExecStart=/usr/local/bin/protonvpn c -f
ExecStop=/usr/local/bin/protonvpn -d
ExecReload=/usr/local/bin/protonvpn c -f

[Install]
WantedBy=multi-user.target

do sudo sudo protonvpn init to get a profile for root.

BIGGEST PROBLEM:

When i turn off my connection, kill-switch disables internet, but reconnecting is not working automatically when i get my connection back, so i get stuck to do it manually again or left without a connection.

**Comment by Rafficer** [comment]
Discussed in #175
