### ISSUE TITLE
[Enhancement] Can it really initialize and autoconnect on boot?

### ISSUE THREAD

**Issue by DouglasQuaid13** [ProtonVPN/linux-cli#175]
Can it really initialize and autoconnect on boot?

I would really love ProtonVPN to start and connect by itself when I turn on my computer. So I guessed the last part of the documentation (enhancements/auto-connect on boot/via systemd service) was supposed to adress this. I've followed its instructions (first time of my life I've written so many command lines so I'm a newbie here, but I think i've handled it, even manage to use nano, yay!). But it does not work, at least not as I hoped. 
Actually I do not understand how it could work since nowhere in the process I'm asked to input my openvpn credentials. How could ProtonVPN-CLI autoconnect to openvpn if it does not know my credentials? Is there something obvious I'm missing or misunderstanding?

Thanks it you can try to help me.

**Comment by d762** [comment]
put this in /etc/systemd/system/protonvpn.service

[Unit]
Description=ProtonVPN
After=syslog.target network-online.target
Wants=network-online.target

[Service]
Type=forking
ExecStart=/usr/local/bin/protonvpn c -f
ExecStop=/usr/local/bin/protonvpn -d
ExecReload=/usr/local/bin/protonvpn c -f

[Install]
WantedBy=multi-user.target

then do exactly this or else it wont work:

sudo sudo protonvpn init (this has to be fully filled out again).

Start it by sudo systemctl enable /etc/systemd/system/protonvpn.service

test it if service restart with 

sudo systemctl start /etc/systemd/system/protonvpn.service

then check if its running with:

sudo systemctl status /etc/systemd/system/protonvpn.service

Explanation: The service has to be running properly when you create it (if not do: sudo chmod +x /etc/systemd/system/protonvpn.service). When you restart protonvpn will be turned on as soon as you make a connection to the internet. There is though a bug:

You have to reconnect manually when you lose connection.

**Comment by Rafficer** [comment]
You pass it your username, that's how the service knows what configuration to use. (Yours.)

@d762 That's also what you missed in your issue. Why go through the hassle and maintain 2 different configurations instead of using one as the usage guide tells you to?

**Comment by d762** [comment]
I tried using User=icbosk but then it claims it needs root.

**Comment by Rafficer** [comment]
Please follow the guide in [USAGE.md](https://github.com/ProtonVPN/linux-cli/blob/master/USAGE.md#via-systemd-service)

**Comment by d762** [comment]
used ENVIROMENT lines, same thing.

**Comment by Rafficer** [comment]
Are you using home dir encryption?

**Comment by d762** [comment]
yes i am. Swap too.

**Comment by Rafficer** [comment]
Then it won't work.

**Comment by d762** [comment]
:(

**Comment by Rafficer** [comment]
Not really. We're working on a bigger update that should solve all the run as root etc issues. But this will still take some time.

**Comment by d762** [comment]
In the meantime should i try and set it up via networkd dispatcher r

**Comment by Rafficer** [comment]
Set up what exactly?

**Comment by d762** [comment]
> In the meantime should i try and set it up via networkd dispatcher to run the pvpn r on network change?

**Comment by Rafficer** [comment]
You can try. Although most of the times the tunnel is stale when a reconnect would be needed instead of breaking entirely. So I'm not sure if this will work great.

**Comment by d762** [comment]
if it can be done...

**Comment by DouglasQuaid13** [comment]
Thank you guys ! you helped me understood I had not initialized my profile before to follow the instructions for the autoconnect on boot ! It works now !
Thanks again !
