### ISSUE TITLE
[BUG] pkexec usage not working

### ISSUE THREAD

**Issue by ceiphr** [ProtonVPN/linux-cli#179]
**Describe the bug**
When I attempt to run the linux-cli client with `pkexec` I get the following error:
```
[!] There has been no profile initialized yet. Please run 'protonvpn init'.
```

**To Reproduce**
1. Run `pkexec sudo protonvpn c -f` in a terminal.

**Expected behavior**
ProtonVPN connects to the fastest server.

**Error Messages/Program Output/Log Messages (~/.pvpn-cli/pvpn-cli.log)**
ProtonVPN outputs:
```
[!] There has been no profile initialized yet. Please run 'protonvpn init'.
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Python Version: 3.8.2
 - ProtonVPN-CLI Version: v2.2.2

Does `pkexec` require some sort of ENV to work like sudo? I can't tell if I'm using it wrong or if it is an issue with the linux-cli client.

**Comment by calexandru2018** [comment]
Hi @ceiphr :)

Firstly, I would like to know, how did you install the CLI ? Was it via Github or PyPi ?

Second, I noticed that you are incorrectly running `pkexec`. The `pkexec` command is part of PolKit, which is a wrapper for the `sudo` command. So you should either use `pkexec` or `sudo`, but not both.

**Comment by ceiphr** [comment]
Thank you @calexandru2018 for the quick response.

I installed through PiPy.

Running pkexec without sudo results in the same output from the cli client.

**Comment by calexandru2018** [comment]
Thanks for the reply @ceiphr 

The PyPi version has not been yet updated. If you would like to use the `pkexec` command, clone this repo instead. Though a new update supporting `pkexec` should be released soon to PyPi.

**Comment by ceiphr** [comment]
Sounds good to me. I'll close this issue now. Thank you.
