### ISSUE TITLE
Links to install instructions not working (404)

### ISSUE THREAD

**Issue by joyofdata** [ProtonVPN/linux-cli#18]
https://github.com/ProtonVPN/linux-cli/blob/master/USAGE.md#updating-protonvpn-cli
https://github.com/ProtonVPN/linux-cli/blob/master/to-add

**Comment by Th3-A6add0n** [comment]
"blob" folder is missing from the repo, so all the instructions and how-tos are missing too.

**Comment by phrxmd** [comment]
Seems like the instructions and how-tos are for a different version of the app?

I get the following error:
```
# protonvpn c --cc CH
Connecting to CH#5 via TCP...
Connected!

A new Update for ProtonVPN-CLI (v2.2.11) is available.
Follow the Update instructions on
https://github.com/ProtonVPN/linux-cli/blob/master/USAGE.md#updating-protonvpn-cli

To see what's new, check out the changelog:
https://github.com/ProtonVPN/linux-cli/blob/master/CHANGELOG.md
```

**Comment by singingotter** [comment]
on attempting to follow links in announcement 404 is result; 

> `A new Update for ProtonVPN-CLI (v2.2.11) is available.

Follow the Update instructions on
https://github.com/ProtonVPN/linux-cli/blob/master/USAGE.md#updating-protonvpn-cli

To see what's new, check out the changelog:
https://github.com/ProtonVPN/linux-cli/blob/master/CHANGELOG.md`

![Screenshot at 2021-07-04 08-08-25](https://user-images.githubusercontent.com/43887498/124384508-9012e400-dc9f-11eb-88f9-fe269dcd3f92.png)

**Comment by calexandru2018** [comment]
Fixes have been pushed and will come next week.

**Comment by calexandru2018** [comment]
Hey, I'm closing this issue as the new updated has fixed this. 

Thank you for contribution!
