### ISSUE TITLE
Implement a country code list.

### ISSUE THREAD

**Issue by Chummpp** [ProtonVPN/linux-cli#188]
**For some reason some one at Protonmail decided not to implement a country list for linux-cli**

I'm always frustrated when I want to find a country code for linux but the option is not available.

**Describe the solution you'd like**
Implement sudo protonvpn linux-cli -connect command in order to show the country list in the terminal the same way sudo protonvpn-cli -connect works.

**Comment by Rafficer** [comment]
Sorry, I don't understand what you mean. There is the connect command that shows you an interactive selection already.

**Comment by calexandru2018** [comment]
I'm closing this issue due to unresponsiveness.
