### ISSUE TITLE
Auto-connect to ProtonVPN at boot with systemd not working

### ISSUE THREAD

**Issue by tpondant** [ProtonVPN/linux-cli#189]
I tried to set up auto-connect via [Systemd](https://github.com/ProtonVPN/linux-cli/blob/master/USAGE.md#via-systemd-service) service and it didn't work.

I created the service unit file, loaded it and enabled it just like mentioned on the usage page.

Unit file:

```
[Unit]
Description=ProtonVPN-CLI auto-connect
Wants=network-online.target

[Service]
Type=forking
ExecStart=/usr/local/bin/protonvpn connect -f
Environment=PVPN_WAIT=300
Environment=PVPN_DEBUG=1
Environment=SUDO_USER=username

[Install]
WantedBy=multi-user.target
```

Output of "sudo which protonvpn":
`/usr/local/bin/protonvpn`

Output of "sudo systemctl status protonvpn-autoconnect":
```
protonvpn-autoconnect.service - ProtonVPN-CLI auto-connect
   Loaded: loaded (/etc/systemd/system/protonvpn-autoconnect.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2020-06-03 09:09:28 CEST; 7h ago
Jun 03 09:09:28 username-computer protonvpn[1049]: 2020-06-03 09:09:28,470 — protonvpn-cli — DEBUG — cli:87 — ['/usr/local/bin/protonvpn', 'connect', '-f']
Jun 03 09:09:28 username-computer protonvpn[1049]: 2020-06-03 09:09:28,470 — protonvpn-cli — DEBUG — cli:88 — USER: username
Jun 03 09:09:28 username-computer protonvpn[1049]: 2020-06-03 09:09:28,471 — protonvpn-cli — DEBUG — cli:89 — CONFIG_DIR: /home/username/.pvpn-cli
Jun 03 09:09:28 username-computer protonvpn[1049]: 2020-06-03 09:09:28,475 — protonvpn-cli — DEBUG — cli:92 — Arguments
Jun 03 09:09:28 username-computer protonvpn[1049]: {'--cc': None, '--fastest': True, '--help': False, '--p2p': False, '--random': False, '--sc': False, '--tor': False, '--version': False, '-p': None, '<
Jun 03 09:09:28 username-computer protonvpn[1049]: 2020-06-03 09:09:28,484 — protonvpn-cli — DEBUG — check_init:471 — Initialized Profile not found
Jun 03 09:09:28 username-computer protonvpn[1049]: [!] There has been no profile initialized yet. Please run 'protonvpn init'.
Jun 03 09:09:28 username-computer systemd[1]: protonvpn-autoconnect.service: Control process exited, code=exited status=1
Jun 03 09:09:28 username-computer systemd[1]: protonvpn-autoconnect.service: Failed with result 'exit-code'.
Jun 03 09:09:28 username-computer systemd[1]: Failed to start ProtonVPN-CLI auto-connect.
```
I even reinitialized the profile as root (copying my whole ~/.pvpn-cli/ folder to /root and removed the SUDO_USER variable from the Unit file). When I restarted, I couldn't access the Internet anymore with or without VPN so I had to remove the service.

**Comment by Rafficer** [comment]
Is your username actually "username", or did you have your local username standing there?

**Comment by tpondant** [comment]
> Is your username actually "username", or did you have your local username standing there?

I do have my local username standing there.

**Comment by Rafficer** [comment]
Do you have encrypted home directories?

**Comment by tpondant** [comment]
> Do you have encrypted home directories?

Yes, my home directory is LUKS encrypted.

**Comment by Rafficer** [comment]
That's the problem as systemd can't look in your homedir for the configuration.

**Comment by tpondant** [comment]
> That's the problem as systemd can't look in your homedir for the configuration.

But shouldn't it have worked when I moved the ~/.pvpn-cli folder to /root and removed the "Environment=SUDO_USER=username" from the Unit file?

**Comment by Rafficer** [comment]
Yes, that should work

**Comment by tpondant** [comment]
Any other way to autoconnect to ProtonVPN at boot?

**Comment by calexandru2018** [comment]
@tpondant take a look at #124 

Feel free to close the issue :)

**Comment by tpondant** [comment]
Would be nice to be able to auto-connect at boot even if we have encrypted home directories.
