### ISSUE TITLE
Does it work for mac ?

### ISSUE THREAD

**Issue by ishandutta2007** [ProtonVPN/linux-cli#196]
This is more of a question that a feature request, if the answer is 'No', then obviously the feature request is to add it for mac as well.
Will the old(archived) one still work for macos https://github.com/ProtonVPN/protonvpn-cli ?

**Comment by Rafficer** [comment]
Please see my reply here: https://github.com/ProtonVPN/linux-cli/issues/31#issuecomment-556062137

As for the old CLI: It may still work, but if there are breaking changes that makes it unusable, it won't get fixed.
