### ISSUE TITLE
[BUG] ProtonVPN linux-cli leaks ipv4 address [probably via WebRTC]

### ISSUE THREAD

**Issue by javaquipped** [ProtonVPN/linux-cli#201]
**Problem**
Local ipv4 address was reported by Google, even when using the latest ProtonVPN `linux-cli` on Linux Mint.

**To Reproduce**
1. Fresh install Linux Mint 19.3 Cinnamon, update all included packages and reboot to update kernel.
2. Install ProtonVPN [according to your instructions](https://protonvpn.com/support/linux-vpn-tool/), initialize, set kill switch to on, deafult to UDP. I'm using basic (paid) plan.
3. Disable ipv6 by altering OS config because of reported bug, also [according to your instructions](https://protonvpn.com/support/disable-ipv6-protocol-linux/).
4. Connect to internet, connect with ProtonVPN, `sudo sysctl -p` to disable ipv6, check interfaces to confirm there is no ipv6.
5. Log into a Google service as a user with Firefox browser. Check your user's devices. You should see your local ip address. 

**Expected behavior**
I expected to see the VPN ip address, as displayed with `protonvpn s`.

**Desktop:**
 - OS: Linux Mint 19.3 on bare metal.
 - Python Version: 3.6.9
 - ProtonVPN-CLI Version: 2.2.4

**Conclusion**
My theory is this is a WebRTC leak.

This is a serious bug, as some people depend on this tool to preserve their privacy, and, in some cases, their actual bodily freedom! Take Hong Kong for example.

We already know that [IPv6 leaks are happening with this tool](https://github.com/ProtonVPN/linux-cli/issues/143) requiring an OS level workaround that can also silently reset to a unprotected state with something as simple as a network reconnect. 

Please make the tool work as advertised (and sold!) or at _the very least_ add detailed documentation and warnings to your product. People's lives may depend on it.

**Comment by Rafficer** [comment]
WebRTC is a browser thing. Configure your browser to block it.

**Comment by javaquipped** [comment]
Sounds like you just took my word for it that it *was* WebRTC rather than some other bug.

I don't know the specifics of WebRTC but, assuming I am correct, this seems like a severe gotcha.

I would hope a VPN program would block all unwanted traffic from a system. Is that not possible in the context of WebRTC?

Also, with such a common technology being used, I would think that including a warning would be appropriate. Do you disagree?

**Comment by Rafficer** [comment]
> Sounds like you just took my word for it that it was WebRTC rather than some other bug.

Yes, because it's not replicatable.

> I would hope a VPN program would block all unwanted traffic from a system. Is that not possible in the context of WebRTC?

It does. But it doesn't prevent a program to tell a website your local IP address over the encrypted tunnel. And if it's a local IP address I don't see the issue anyway. ISP IP would be something different.

> Also, with such a common technology being used, I would think that including a warning would be appropriate. Do you disagree?

I don't think it's appropriate for a program to spam a user with warnings of potential issues they could have when they don't follow best practices. There's far more to being private than turning on a VPN.

**Comment by javaquipped** [comment]
Thank you for the reply. If you're willing, can you help me to understand some of these things? I have some genuine questions.

> > Sounds like you just took my word for it that it was WebRTC rather than some other bug.
> 
> Yes, because it's not replicatable.

This I don't understand because I wrote out the exact recipe for the behaviour. I assume that the issue itself is out of scope because of how it has been closed, but that seems to be a separate concern. How could I write a better "To Reproduce" section? or are you simply saying WebRTC is out of scope for support?

> > I would hope a VPN program would block all unwanted traffic from a system. Is that not possible in the context of WebRTC?
> 
> It does. But it doesn't prevent a program to tell a website your local IP address over the encrypted tunnel. And if it's a local IP address I don't see the issue anyway. ISP IP would be something different.

What I mean by local address, is the endpoint ipv4 address. 

Are you suggesting that WebRTC could be doing some kind of LAN network discovery, which from another device, requests the local IP address [and thus there is no tunnel ]? or it is querying a local file where that address is written? Otherwise I do not see how there would be a revealation of a local IP address, since the site itself is being accessed over the tunnel at that point. Where is my reasoning wrong here?

> > Also, with such a common technology being used, I would think that including a warning would be appropriate. Do you disagree?
> 
> I don't think it's appropriate for a program to spam a user with warnings of potential issues they could have when they don't follow best practices. There's far more to being private than turning on a VPN.

Acknowleded, and I agree.

Thank you again for taking the time to reply.

**Comment by Rafficer** [comment]
> This I don't understand because I wrote out the exact recipe for the behaviour. I assume that the issue itself is out of scope because of how it has been closed, but that seems to be a separate concern. How could I write a better "To Reproduce" section? or are you simply saying WebRTC is out of scope for support?

WebRTC is basically out of scope of the program. Your "how to reproduce" was good, what I wanted to say is that this is not a universal issue that anyone can run into. I actually did set up Linux Mint and logged in to Google the way you described, and Google simply showed me the VPN IP address.

> Are you suggesting that WebRTC could be doing some kind of LAN network discovery, which from another device, requests the local IP address [and thus there is no tunnel ]? or it is querying a local file where that address is written? Otherwise I do not see how there would be a revealation of a local IP address, since the site itself is being accessed over the tunnel at that point. Where is my reasoning wrong here?

The only leaks I've seen with WebRTC are of the local IP (not the public IP from your ISP). So basically what you get when running `ip address show`.
