### ISSUE TITLE
Can't update CLI: AssertionError: Egg-link /dev/shm/protonvpn-cli-ng does not match installed location of protonvpn-cli

### ISSUE THREAD

**Issue by pcommander** [ProtonVPN/linux-cli#205]
Unable to update ProtonVPN CLI and Python due to Python not working and obstacles preventing me from installing the latest Python/pip.
I use Linux Mint 18 Mate 64-bit, which is an LTS distro and supports only a deprecated version of Python/pip.
I have ProtonVPN CLI 2.2.2 installed and I depend on the CLI to connect to the VPN, so I must resolve this issue or I fear eventually the CLI will break to the point of unusability.
I tried the update commands per https://protonvpn.com/support/linux-vpn-tool/ to no avail.
Neither CLI nor Python/pip will update.
I even installed the latest Python3.5 from git and 'python --version' returns Python 2.7.12.
The Mint forum suggested installing Anaconda python https://anaconda.org/anaconda and https://modules.readthedocs.io/en/latest/ to maintain multiple versions of Python because only installing the latest Python will break my OS.
However, this is getting extremely time-consuming and over my head technically.

Therefore, I'm requesting that the command line tool please be built with whatever version you're using baked into the CLI package so the dependency is met regardless of what version the OS supports.
Compiling the package with Python included, releasing the CLI as a Docker, or using another language that requires no special maintenance would really make this a lot more practical for me other Linux users to adopt.
(By the way, I use LTS distros because rolling distros constantly update package versions which breaks things requiring advanced skills and time to fix if it's fixable at all, which is impractical for an OS run by an individual.)
If that can't be done I request your advice on how to proceed with updating and maintaining two versions of Python/pip and continuing with upgrade of CLI tool.

Thanks

**Comment by Rafficer** [comment]
Try using python3 instead of python, which points to python2 on many distros.

**Comment by pcommander** [comment]
On Thu, 02 Jul 2020 04:41:04 -0700
Rafficer <notifications@github.com> wrote:

"Try using python3 instead of python, which points to python2 on many
distros."

I installed Python3.5 and do:
#!/usr/bin/python3.5
in the terminal but the update process uses 2.7 anyway.
I don't know how to make it use 3.5.
Neither protonvpn-cli nor pip will update. I get errors.
I posted about it on Linux Mint forums:
https://forums.linuxmint.com/viewtopic.php?f=47&t=322581

Essentially their answer was:
"FWIW if you need to operate several versions of python I recommend
using relevant versions of Anaconda python
https://anaconda.org/anaconda and Environment Modules
https://modules.readthedocs.io/en/latest/ to keep them from interfering
with each other and with the system python. Anaconda itself has a tool
for different python environments and you can equally well use that.
Installing Anaconda probably gives you much more than you need but
there is a Miniconda installer which basically gives you python and the
administration tool conda. Starting with that you can then install what
you need which may be a good idea if your space is limited. I you
choose to use Anaconda python I recommend not letting it initialize on
startup. You get that option during installation. Let Environment
Modules do the initialization instead or if you choose to let Anaconda
handle it all you have to do to start a session is to source a file
containing the path to the Anaconda installations bin-folder prepended
to the PATH environment variable. The reason is that Anconda brings
its' own version of qt which has been known to interfere with system
startup. Initializing it on startup also hides system python from the
system which you don't really want. If you choose to use Environment
Modules its' initialization works best if you point /bin/sh
to /bin/bash instead of /bin/dash. There are also some other quirks
regarding Environment Modules on a Debian offspring. You can read about
it here: viewtopic.php?f=47&t=279377

https://conda.io/en/latest/miniconda.html
https://modules.readthedocs.io/en/latest/
https://pythonbasics.org/virtualenv/
"

Does that seem good to you, or is there something else I can try first?
Thanks

**Comment by Rafficer** [comment]
Linux Mint 18 comes with Python 3.5 in the repositories, which is fine for running the CLI. Using pip3 (as the documentation says) should point to that version of python. If it doesn't, you broke your python installation.

**Comment by calexandru2018** [comment]
Hi @pcommander,

Did the instructions that Rafficer provide you with help in solving your issue ?

**Comment by pcommander** [comment]
I'll get back to you as soon as possible. There are multiple things I
have to sort out. Thank you.

**Comment by pcommander** [comment]
There are multiple things I have to sort out but I'll get back to
Rafficer as soon as possible. It's not resolved yet. Thank you.

**Comment by pcommander** [comment]
The problem is Python2.7 is a core component of my particular distro
and the forum tells me it will "clobber your entire Linux Mint
installation".

They suggested installing 3.5 alongside 2.7 and managing versions with
'Anaconda':

"
FWIW if you need to operate several versions of python I recommend
using relevant versions of Anaconda python
https://anaconda.org/anaconda and Environment Modules
https://modules.readthedocs.io/en/latest/ to keep them from interfering
with each other and with the system python. Anaconda itself has a tool
for different python environments and you can equally well use that.
Installing Anaconda probably gives you much more than you need but
there is a Miniconda installer which basically gives you python and the
administration tool conda. Starting with that you can then install what
you need which may be a good idea if your space is limited. I you
choose to use Anaconda python I recommend not letting it initialize on
startup. You get that option during installation. Let Environment
Modules do the initialization instead or if you choose to let Anaconda
handle it all you have to do to start a session is to source a file
containing the path to the Anaconda installations bin-folder prepended
to the PATH environment variable. The reason is that Anconda brings
its' own version of qt which has been known to interfere with system
startup. Initializing it on startup also hides system python from the
system which you don't really want. If you choose to use Environment
Modules its' initialization works best if you point /bin/sh
to /bin/bash instead of /bin/dash. There are also some other quirks
regarding Environment Modules on a Debian offspring. You can read about
it here: viewtopic.php?f=47&t=279377
"

Does that seem like a reasonable solution to you? Thank you.

**Comment by pcommander** [comment]
"Try using python3 instead of python, which points to python2 on many
distros."

In the terminal I issued the command:
$ #!/usr/bin/python3

whereas before I issued:
$ #!/usr/bin/python3.5

I attempted to update pip3:
$ sudo -H pip3 install --upgrade pip3

which results in:
Collecting pip3
  Could not find a version that satisfies the requirement pip3 (from
versions: ) No matching distribution found for pip3
You are using pip version 8.1.1, however version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip'
command.

I attempted to update protonvpn-cli with:
$ sudo -H pip3 install protonvpn-cli --upgrade

which results in:
Collecting protonvpn-cli
  Downloading
https://files.pythonhosted.org/packages/b2/11/bb1ecbfaec27da701f9e9c18a42c7be8d37295bff4efe693f88ab9da5276/protonvpn_cli-2.2.4-py3-none-any.whl
Requirement already up-to-date: pythondialog
in ./.local/lib/python3.5/site-packages (from protonvpn-cli)
Requirement already up-to-date: requests
in /usr/local/lib/python3.5/dist-packages (from protonvpn-cli)
Requirement already up-to-date: jinja2
in /usr/local/lib/python3.5/dist-packages (from protonvpn-cli)
Requirement already up-to-date: docopt
in ./.local/lib/python3.5/site-packages (from protonvpn-cli)
Requirement already up-to-date: chardet<4,>=3.0.2
in ./.local/lib/python3.5/site-packages (from requests->protonvpn-cli)
Collecting certifi>=2017.4.17 (from requests->protonvpn-cli)
Downloading
https://files.pythonhosted.org/packages/5e/c4/6c4fe722df5343c33226f0b4e0bb042e4dc13483228b4718baf286f86d87/certifi-2020.6.20-py2.py3-none-any.whl
(156kB) 100% |████████████████████████████████| 163kB 163kB/s
Collecting idna<3,>=2.5 (from requests->protonvpn-cli) Downloading
https://files.pythonhosted.org/packages/a2/38/928ddce2273eaa564f6f50de919327bf3a00f091b5baba8dfa9460f3a8a8/idna-2.10-py2.py3-none-any.whl
(58kB) 100% |████████████████████████████████| 61kB 200kB/s Requirement
already up-to-date: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
in /usr/local/lib/python3.5/dist-packages (from
requests->protonvpn-cli) Requirement already up-to-date:
MarkupSafe>=0.23 in /usr/local/lib/python3.5/dist-packages (from
MarkupSafe>jinja2->protonvpn-cli) Installing collected packages:
MarkupSafe>protonvpn-cli, certifi, idna Found existing installation:
MarkupSafe>protonvpn-cli 2.2.2 Exception: Traceback (most recent call
MarkupSafe>last): File
MarkupSafe>"/usr/lib/python3/dist-packages/pip/basecommand.py", line
MarkupSafe>209, in main status = self.run(options, args) File
MarkupSafe>"/usr/lib/python3/dist-packages/pip/commands/install.py",
MarkupSafe>line 335, in run prefix=options.prefix_path, File
MarkupSafe>"/usr/lib/python3/dist-packages/pip/req/req_set.py", line
MarkupSafe>726, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line
692, in uninstall '(at %s)' % (link_pointer, self.name, dist.location)
AssertionError: Egg-link /dev/shm/protonvpn-cli-ng does not match
installed location of protonvpn-cli
(at /usr/local/lib/python3.5/dist-packages) You are using pip version
8.1.1, however version 20.1.1 is available. You should consider
upgrading via the 'pip install --upgrade pip' command.

It says I'm using pip 8.1.1 which is true for Python3.5 but not 2.7.
$ pip --version
pip 20.1.1 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)

$ pip3 --version
pip 8.1.1 from /usr/lib/python3/dist-packages (python 3.5)

If Anaconda or Miniconda seems like a good solution to you for managing
Python will it also fix the pip version for 3.5?

Thank you.

**Comment by Rafficer** [comment]
> I attempted to update pip3:
> $ sudo -H pip3 install --upgrade pip3

The package is called `pip`. If you want to update to the latest version, you can do `sudo python3 -m pip install --upgrade pip`. Though I doubt this will help you.

>   File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line
692, in uninstall '(at %s)' % (link_pointer, self.name, dist.location)
AssertionError: Egg-link /dev/shm/protonvpn-cli-ng does not match
installed location of protonvpn-cli

This seems to be more the issue.

What's the output of `ls -lah ~/.local/lib/python3.5/site-packages/ | grep -i protonvpn`?

What's the output of `ls -lah /usr/local/lib/python3.5/dist-packages`?

Also, please properly format the output of commands here on Github. It's really hard to distinguish them from your own words.

**Comment by pcommander** [comment]
It appears your advice worked. Both pip and CLI are now updated.

And there is no more "AssertionError: Egg-link /dev/shm/protonvpn-cli-ng
does not match" error.

I replied to you via e-mail not github, which I hardly ever use.

I only got a github account just for this.

I don't know how to format it but next time I'll make it easier to
distinguish.

Thank you. You may close the ticket.

**Comment by Rafficer** [comment]
For future reference: https://guides.github.com/features/mastering-markdown/

This should also work when replying via Email.
