### ISSUE TITLE
Proton VPN failing to start up after following the guide

### ISSUE THREAD

**Issue by vincpa** [ProtonVPN/linux-cli#214]
Hi,

I am able to start protonvpn by entering the command line `protonvpn c -f` but for some reason it fails when it's set to happen on boot using systemctl. Can anyone help me please?

![image](https://user-images.githubusercontent.com/441719/87938148-7356be00-cad9-11ea-9aaa-1a3d06528ff5.png)

**Comment by Rafficer** [comment]
Encrypted home directory?

**Comment by vincpa** [comment]
Yes my home directory is encrypted. Is this a problem with the guide on github or is it a problem with systemctl? If this is a systemctl thing I'll find a solution online.

**Comment by Rafficer** [comment]
That's the problem. It doesn't work with encrypted home directories.

**Comment by vincpa** [comment]
That's a bit a problem considering ProntonVPN prides itself on security :)

I'm going to try and find another way to get this to happen on startup and submit a pull request for the instructions.

In the meantime, can you recommend another way to use VPN in Linux?

**Comment by Rafficer** [comment]
Yeah, it's just the way the CLI works. All your config is in your home dir and you want root to access that before unlocking it. You see the problem.

You can set up the CLI under root. That should work.

**Comment by vincpa** [comment]
OK, I solved this by running proton VPN set up as root. Not by doing a `sudo` but by switching to root using `su` and setting up the config there. After that, running protonvpn as root using systemctl is not a problem.
