### ISSUE TITLE
When I enable the kill switch I am unable to access machines on my LAN

### ISSUE THREAD

**Issue by badmotorfinger** [ProtonVPN/linux-cli#223]
**Describe the bug**

When I enable the kill switch in Linux Mint 19 and I use the VPN (`sudo protonvpn c -f`) then I cannot access local resources on my LAN.

**To Reproduce**
1. Enable killswitch in `pvpn-cli.cfg`
2. Start up vpn using `sudo protonvpn c -f`
3. Try and access LAN IP addresses and it does not work

**Expected behavior**

I expect to connect to LAN resources

**Desktop (please complete the following information):**

OS: Linux Mint 19.3 Tricia x86_64
Kernel: 5.4.0-42-generic
ProtonVPN-CLI v2.2.4
Python: 3.6.9

**Comment by Zoarial94** [comment]
I believe this is the expected behavior. The killswitch prevents any leakage outside of the VPN, even if the tunnel was unexpectedly killed. You are probably looking for the split tunnel option. I have started a fork of this repo and I am looking into adding exceptions to the killswitch.

**Comment by badmotorfinger** [comment]
Killswitch is meant to disable your network connection if the VPN connection drops. I don't see how that has anything to do with my LAN addresses.

**Comment by Rafficer** [comment]
The Kill Switch prevents anything from leaving your device that doesn't go over the VPN interface. So it also prevents you from communicating with your local network.

**Comment by badmotorfinger** [comment]
OK fair enough.

You might want to update the official documentation because it doesn't mention that specifically, at all says is that if the VPN is disconnected your traffic is stopped.

https://protonvpn.com/blog/macos-vpn-kill-switch/
https://protonvpn.com/secure-vpn
