### ISSUE TITLE
[Information]

### ISSUE THREAD

**Issue by mitcon3** [ProtonVPN/linux-cli#227]
I see from one of the files on the Code tab that the current version of the CLI is 2.2.4. I'm currently on that version.

Is there a way to check for the Current Version and do an Update using the CLI? I found a comment on the Proton site that you can do **pvpn -update** to accomplish this. I do not believe the Proton person is correct for v2.2.4. When I do that the help text is presented.

Thanks,
Mitch

**Comment by Rafficer** [comment]
That's an old command and doesn't exist in this version of the CLI.

The CLI auto checks for new versions and displays a message if a new version is available.
