### ISSUE TITLE
[BUG] importlib.metadata.PackageNotFoundError

### ISSUE THREAD

**Issue by AnkS4** [ProtonVPN/linux-cli#229]
**Describe the bug**
Getting `importlib.metadata.PackageNotFoundError: protonvpn-cli` error.

**To Reproduce**
1. Clone the repository, cd linux-cli, pip3 install -e .
2. Enter `sudo protonvpn init`

**Expected behavior**
Initialize without error.

**Error Messages/Program Output/Log Messages (~/.pvpn-cli/pvpn-cli.log)**
```
Traceback (most recent call last):
  File "/home/anks/.local/bin/protonvpn", line 33, in <module>
    sys.exit(load_entry_point('protonvpn-cli', 'console_scripts', 'protonvpn')())
  File "/home/anks/.local/bin/protonvpn", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 504, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: protonvpn-cli
```

**Desktop:**
 - OS: Manjaro XFCE 20.1
 - Python Version: Python 3.8.5
 - ProtonVPN-CLI Version: ProtonVPN CLI v.2.2.4

**Additional Information:**
Without sudo I'm getting this output:
```
$ protonvpn init
[!] The program was not executed as root.
[!] Please run as root.
```

**Comment by Rafficer** [comment]
Did you install it with sudo, so it's system wide?

**Comment by AnkS4** [comment]
No.

That might be the reason.
