### ISSUE TITLE
Suggestion placing Issue Template as sticky for bug reports, enable labelling, to expedite resolutions

### ISSUE THREAD

**Issue by singingotter** [ProtonVPN/linux-cli#23]
#2 Update issue **templates**
Many (most?) issue reports do not follow guidelines in Reporting Template [https://github.com/ProtonVPN/linux-cli/pull/2/commits/9434001013ca1987d84ba4ed956f4eb2f2b11ef4]
Having the template displayed prominently as a sticky "how to report issues" at the head of the github issue page would help everyone. @protonvpn
Also, although labels are available in the git (including 'bug', 'help wanted', 'feature request') it does not seem currently possible to use these when creating a report . Suggested enabling this so contributors can assist categorizing reports.

**Comment by calexandru2018** [comment]
Hey @singingotter 

Templates have been merged and will be coming with next release.
