### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lorenzojavier** [ProtonVPN/linux-cli#236]
**Describe the bug**
I can't log in. authentication failed.

**To Reproduce**
I ran:

sudo protonvpn init

When prompted, entered my ProtonVpn username (**********@protonmail.com) and password.
After finishing the setup, I ran:

sudo protonvpn connect

After choosing what server, wether to use UDP or TCP, it starts connecting... and I get:

[!] Authentication failed. 
[!] Please make sure that your Username and Password is correct

**Expected behavior**
I expected to connect to the VPN network.

**Error Messages/Program Output/Log Messages (~/.pvpn-cli/pvpn-cli.log)**
2020-09-21 11:37:16,021 — protonvpn-cli — DEBUG — call_api:65 — Successful json response
2020-09-21 11:37:16,026 — protonvpn-cli — DEBUG — openvpn_connect:474 — OpenVPN process started
2020-09-21 11:37:27,061 — protonvpn-cli — DEBUG — openvpn_connect:517 — Authentication failure

**Desktop (please complete the following information):**
 - OS: elementary OS 5.1.7 Hera
 - Python Version: Python 3.6.9
 - ProtonVPN-CLI Version: ProtonVPN CLI v.2.2.4

**Additional context**
Using this same credentials I can log in at protonvpn.com.

Any Ideas about this? Maybe I'm I doing something wrong?
Thank you in any case, for taking time and reading this.

**Comment by Rafficer** [comment]
Please read the obtrusive init message the CLI prints:

![image](https://user-images.githubusercontent.com/19485606/93783091-9c0b4900-fc2b-11ea-9050-976b5a569f07.png)

**Comment by calexandru2018** [comment]
You should type your openvpn/ikev2 credentials and not your protonvpn ones.

**Comment by lorenzojavier** [comment]
Thank you very much!
:D
