### ISSUE TITLE
[Enhancement] Make call to `manage_dns` optional.

### ISSUE THREAD

**Issue by initbar** [ProtonVPN/linux-cli#238]
**Is your feature request related to a problem? Please describe.**

The [manage_dns](https://github.com/ProtonVPN/linux-cli/blob/master/protonvpn_cli/connection.py#L541) is trying to temporarily control my DNS in `/etc/resolv.conf`, but I wish this was optional. My `resolv.conf` is an immutable file (manually `chattr +i`) that has a static nameserver to `127.0.0.53` ([dnscrypt](https://github.com/DNSCrypt/dnscrypt-proxy)). However, whenever I try to connect to ProtonVPN, I have to manually unset this immutable flag to prevent PVPN connection from hanging.

![Screenshot_2020-09-24_23-52-21](https://user-images.githubusercontent.com/12630151/94224680-0be63180-fec1-11ea-9705-7fd1de0836c9.png)

**Describe the solution you'd like**

The best case scenario is that the leak protection has an optional opt-out. But otherwise, the [manage_dns](https://github.com/ProtonVPN/linux-cli/blob/master/protonvpn_cli/connection.py#L541) should check whether the target `resolvconf_path` is immutable ([stat.UF_IMMUTABLE](https://docs.python.org/3/library/stat.html#stat.UF_IMMUTABLE)) through stat'ing the file and skip the leak protection/backup/restore.

**Comment by initbar** [comment]
I can also work on the PR if the suggested solution of skipping the **manage_dns** through file attributes looks good.

**Comment by Rafficer** [comment]
If you disable leak protection it shouldn't try to access this file.

**Comment by initbar** [comment]
Awesome, that works. Thank you.
