### ISSUE TITLE
[Enhancement] Reverse Split Tunneling

### ISSUE THREAD

**Issue by developomp** [ProtonVPN/linux-cli#239]
Hi. I am a linux user of protonVPN (will be calling it pvn from this point onward) and wanted to use pvn to connect to one specific IP address.
I used [this](https://www.ipaddressguide.com/cidr) tool as mentioned in [this guide](https://github.com/ProtonVPN/linux-cli/blob/master/USAGE.md#split-tunneling) and came up with a range that excludes the IP address I want pvn to use.

Google (`172.217.161.142`), for example, the range would be from `0.0.0.0` to `172.217.161.141` and from `172.217.161.143` to `255.255.255.255`. Following is the result:
```
0.0.0.0/1
128.0.0.0/3
160.0.0.0/5
168.0.0.0/6
172.0.0.0/9
172.128.0.0/10
172.192.0.0/12
172.208.0.0/13
172.216.0.0/16
172.217.0.0/17
172.217.128.0/19
172.217.160.0/24
172.217.161.0/25
172.217.161.128/29
172.217.161.136/30
172.217.161.140/31
172.217.161.143/32
172.217.161.144/28
172.217.161.160/27
172.217.161.192/26
172.217.162.0/23
172.217.164.0/22
172.217.168.0/21
172.217.176.0/20
172.217.192.0/18
172.218.0.0/15
172.220.0.0/14
172.224.0.0/11
173.0.0.0/8
174.0.0.0/7
176.0.0.0/4
192.0.0.0/2
```
I pasted this to `~/.pvpn-cli/split_tunnel.txt` but apparently pvn doesn't work when the exclusion list is too long.

When I start pvn the result shows that I'm connected:
```
[pomp@pomp ~]$ sudo protonvpn c -f
Connecting to JP-FREE#2 via TCP...
[!] Connection failed. Reverting all changes...
There is already a VPN connection running.
Terminating previous connection...
Connected!        <------- here
```

But tests show that pvn isn't running (Replaced Personal info with `*`):
```
[pomp@pomp ~]$ sudo protonvpn s
Status:     Disconnected
IP:         ***.**.***.**
ISP:        ***** *******
```
```
[pomp@pomp ~]$ sudo protonvpn d
No connection found.
```

It would be very helpful if we can toggle between "whitelist" and "blacklist" option where whitelist option makes the device use pvn when connecting to specified addressed and blacklist option is what pvn is now.

+EDIT
After a bit of research, I found out that this "whitelist" I was talking about is called reverse split tunneling

**Comment by developomp** [comment]
I'd really like to see Reverse Split tunneling implemented. Bring me the manager!
But seriously may I at least get a feedback?

**Comment by Utopiah** [comment]
Might be good to consolidate #230 instead then close here.

**Comment by developomp** [comment]
> Might be good to consolidate #230 instead then close here.

agreed. Closing this issue.
