### ISSUE TITLE
[BUG] Python 3.9.0 Update breaks cli

### ISSUE THREAD

**Issue by danechambers** [ProtonVPN/linux-cli#257]
**Describe the bug**
Update python version to 3.9.0. Cli crashes when executing any command (including help).

**To Reproduce**
 Run any protonvpn command. 
For example
```
protonvpn --help
```
or
```
protonvpn --version
```

**Expected behavior**
It should run normally.

**Error Messages/Program Output/Log Messages (~/.pvpn-cli/pvpn-cli.log)**
stacktrace
```
Traceback (most recent call last):
  File "/usr/bin/protonvpn", line 33, in <module>
    sys.exit(load_entry_point('protonvpn-cli==2.2.4', 'console_scripts', 'protonvpn')())
  File "/usr/bin/protonvpn", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: protonvpn-cli
```
there are no logs generated when running the cli.

**Desktop (please complete the following information):**
 - OS: Arch
 - Python Version: 3.9.0
 - ProtonVPN-CLI Version: 2.2.4

**Comment by Rafficer** [comment]
I'm guessing that the CLI is installed in the python3.8 path folder. Can you reinstall it via pip?

**Comment by Henry0w** [comment]
Trying to install it results in:
```
╰─➤  pip3 install --user protonvpn-linux-gui
ERROR: Could not find a version that satisfies the requirement protonvpn-linux-gui (from versions: none)
ERROR: No matching distribution found for protonvpn-linux-gui
```
I tried installing python 3.8 alongside 3.9, but that did not seem to fix anything

**Comment by danechambers** [comment]
Thank you. Installing from pip worked. It does seem a bit odd as the arch pkgbuild I was using https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=protonvpn-cli-ng just runs
```
python setup.py install --optimize=1 --root="$pkgdir"
```
Maybe one of the dependencies for the pkgbuild is out of date? Anyways, thanks again for your help!
