### ISSUE TITLE
[Enhancement] do not store cleartext password

### ISSUE THREAD

**Issue by hexpwn** [ProtonVPN/linux-cli#261]
**Is your feature request related to a problem? Please describe.**
The tool is storing, in **cleartext**, the password to the account at `.pvpn-cli/pvpnpass`; which in turn can also be the users protonmail password. I feel this is very insecure.

**Describe the solution you'd like**
Password should be salted and hashed before being stored locally.

**edit**: I just realized there are separate credentials for OpenVPN and Proton services, but I still would consider it a proper security measure to have these OpenVPN credentials salted and hashed instead of being stored in cleartext.

**Comment by calexandru2018** [comment]
Hey @hexpwn 

No further commits will be made to the community project as the official cli has been released, you can find here: https://protonvpn.com/blog/linux-vpn-cli-beta/

**Comment by hexpwn** [comment]
hi @calexandru2018 thanks for the heads up
so I'm understanding this new version is not open source?
any idea when other distros will be supported?
thank you

**Comment by calexandru2018** [comment]
Hey @hexpwn 
Please do read the blog announcement and the kb article as most of your questions are answered there.

In regards to open-source, everything will be released once the packages as considered as stable.
