### ISSUE TITLE
[BUG] 'bool' object is not subscriptable

### ISSUE THREAD

**Issue by Commmodorian** [ProtonVPN/linux-cli#264]
Alright lads, gonna just let you know that I have zero experience with Python, but have completed a college course on c++ so I should be able to get the gist of whatever you fellas say is wrong.

Nonetheless, I'm getting this error log (in terminal):
<b>Traceback (most recent call last):
  File "/usr/bin/protonvpn-cli", line 11, in <module>
    load_entry_point('protonvpn-cli==3.1.0', 'console_scripts', 'protonvpn-cli')()
  File "/usr/lib/python3/dist-packages/protonvpn_cli/main.py", line 21, in main
    ProtonVPNCLI()
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli.py", line 46, in __init__
    getattr(self, args.command)()
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli.py", line 111, in connect
    self.cli_wrapper.connect(args)
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli_wrapper.py", line 121, in connect
    conn_status[ConnectionMetadataEnum.SERVER],
TypeError: 'bool' object is not subscriptable </b>

Now my only guess as to what is happening is that conn_status is a bool object and something is trying to call that while already being in a script? Again, no experience with python.

Here's my setup:
HP Stream 14 running Lubuntu 20.10 (Ubuntu with LXQt Desktop Environment)

I've used ProtonVPN linux command line tool with this laptop before, but running a different OS, that being vanilla Ubuntu, so it might be something to do with Lubuntu, but I highly doubt it.
Anyways, let me know when you guys can get back to me.

**Comment by calexandru2018** [comment]
Hey @Commmodorian 

This issue is not particular to this version of the CLI as this is a community build project. Instead, you error seems to originate from the official CLI tool that is in beta at the current moment. Please close the issue, and either contact support or email to: linux-beta(at)protonvpn.com
