### ISSUE TITLE
[BUG] protonvpn-cli is not working on Kali Linux - "has no attribute 'kwallet'" Error

### ISSUE THREAD

**Issue by baget** [ProtonVPN/linux-cli#266]
**Describe the bug**
getting `AttributeError: module 'keyring.backends' has no attribute 'kwallet'`

when running protonvpn-cli on Kali Linux 2020.4

**To Reproduce**
1. install proton-cli according to https://protonvpn.com/support/official-linux-client/
2. try to run protonvpn-cli
**Expected behavior**

**Error Messages/Program Output/Log Messages (~/.pvpn-cli/pvpn-cli.log)**
```
kali@kali:~$ protonvpn-cli 
Traceback (most recent call last):
  File "/usr/bin/protonvpn-cli", line 11, in <module>
    load_entry_point('protonvpn-cli==3.1.0', 'console_scripts', 'protonvpn-cli')()
  File "/usr/lib/python3/dist-packages/protonvpn_cli/main.py", line 20, in main
    from .cli import ProtonVPNCLI
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli.py", line 9, in <module>
    from .cli_wrapper import CLIWrapper
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli_wrapper.py", line 32, in <module>
    from protonvpn_nm_lib.services.user_manager import UserManager
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/services/user_manager.py", line 10, in <module>
    from .user_session_manager import UserSessionManager
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/services/user_session_manager.py", line 14, in <module>
    class UserSessionManager:
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/services/user_session_manager.py", line 16, in UserSessionManager
    keyring.backends.kwallet.DBusKeyring,
AttributeError: module 'keyring.backends' has no attribute 'kwallet'


```
**Desktop (please complete the following information):**
 - OS: Kali 2020.4
 - Python Version: Python 3.9.1
 - ProtonVPN-CLI Version: lastest

**Comment by yekteniya** [comment]
Getting the exact same error on Debian buster

**Comment by tschan-its** [comment]
The same here:

- Debian Bullseye
- Kernel: 5.9.0-5-amd64
- Gnome 3.38.2

- Python 3.9.1
- keyring:  21.6.0
- keyring --list-backends: (keyring.backends.SecretService.Keyring (priority: 5) | keyring.backends.fail.Keyring (priority: 0) | keyring.backends.chainer.ChainerBackend (priority: -1) ) 
- ProtonVPN-CLI latest version

Could it be a problem with the packaged dependencies of keyring?

**Comment by calexandru2018** [comment]
Hey all 👋

This issue is in regards to the official CLI and not the community build, which is this one.
Please either contact support or send an report to the email that can be found in protonvpn-cli --help.

Please close this issue.

**Comment by baget** [comment]
just for reference:
https://github.com/jaraco/keyring/issues/483

it solve the issue

**Comment by JDsWebService** [comment]
> The same here:
> 
>     * Debian Bullseye
> 
>     * Kernel: 5.9.0-5-amd64
> 
>     * Gnome 3.38.2
> 
>     * Python 3.9.1
> 
>     * keyring:  21.6.0
> 
>     * keyring --list-backends: (keyring.backends.SecretService.Keyring (priority: 5) | keyring.backends.fail.Keyring (priority: 0) | keyring.backends.chainer.ChainerBackend (priority: -1) )
> 
>     * ProtonVPN-CLI latest version
> 
> 
> Could it be a problem with the packaged dependencies of keyring?



> Getting the exact same error on Debian bullseye



> **Describe the bug**
> getting `AttributeError: module 'keyring.backends' has no attribute 'kwallet'`
> 
> when running protonvpn-cli on Kali Linux 2020.4
> 
> **To Reproduce**
> 
>     1. install proton-cli according to https://protonvpn.com/support/official-linux-client/
> 
>     2. try to run protonvpn-cli
>        **Expected behavior**
>        A clear and concise description of what you expected to happen.
> 
> 
> **Error Messages/Program Output/Log Messages (~/.pvpn-cli/pvpn-cli.log)**
> 
> ```
> kali@kali:~$ protonvpn-cli 
> Traceback (most recent call last):
>   File "/usr/bin/protonvpn-cli", line 11, in <module>
>     load_entry_point('protonvpn-cli==3.1.0', 'console_scripts', 'protonvpn-cli')()
>   File "/usr/lib/python3/dist-packages/protonvpn_cli/main.py", line 20, in main
>     from .cli import ProtonVPNCLI
>   File "/usr/lib/python3/dist-packages/protonvpn_cli/cli.py", line 9, in <module>
>     from .cli_wrapper import CLIWrapper
>   File "/usr/lib/python3/dist-packages/protonvpn_cli/cli_wrapper.py", line 32, in <module>
>     from protonvpn_nm_lib.services.user_manager import UserManager
>   File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/services/user_manager.py", line 10, in <module>
>     from .user_session_manager import UserSessionManager
>   File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/services/user_session_manager.py", line 14, in <module>
>     class UserSessionManager:
>   File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/services/user_session_manager.py", line 16, in UserSessionManager
>     keyring.backends.kwallet.DBusKeyring,
> AttributeError: module 'keyring.backends' has no attribute 'kwallet'
> ```
> 
> **Desktop (please complete the following information):**
> 
>     * OS: Kali 2020.4
> 
>     * Python Version: Python 3.9.1
> 
>     * ProtonVPN-CLI Version: lastest

Can confirm that [this](https://github.com/jaraco/keyring/issues/483#issuecomment-752306119) solves the issue.

**Comment by Dean-Christian-Armada** [comment]
> just for reference:
> [jaraco/keyring#483](https://github.com/jaraco/keyring/issues/483)
> 
> it solve the issue

This one helped me solved the issue in my Kali Linux

**Comment by rustysun9** [comment]
This didnt work for me :(
I updated all pip3 modules and after doing this, i cannot get protonvpn-cli to work.
Even after keyring was downgraded to 21.5.0 I still receive the same error as it is stated above.

**Comment by thomasoliveira** [comment]
@rustysun9 , what worked for me was to run KWalletManager first, to enable the kwallet system.
