### ISSUE TITLE
Cannot access internet without activating Proton VPN since yesterdays upgrade

### ISSUE THREAD

**Issue by joyofdata** [ProtonVPN/linux-cli#27]
Yesterday I followed https://protonvpn.com/support/linux-vpn-setup/ to install the official protonvpn-cli.
Now after a restart I cannot access the internet. After a some confusion I found that I have to activate VPN Connection ("ProtonVPN DE #10" in my case) which was apparently configured during the login or connect step after installing protonvpn-cli. 

![image](https://user-images.githubusercontent.com/3748975/124723485-652cc800-df0b-11eb-80cd-eed5d8cbe4a1.png)

Why? What's going on here?

I mean, I didn't ask for that. I just wanted to install the CLI command and that's it. I logged in with it and and connected. If I don't connect manually I'd like to use internet as is, obviously.

Before I was happy with the community CLI program and was also using an OpenVPN config manually. But if I didn't select it I could still access the Internet. Why is it blocked now???

(Linux Mint 20.1)

**Comment by calexandru2018** [comment]
This is discussed here: https://github.com/ProtonVPN/linux-app/issues/20
