### ISSUE TITLE
[BUG] "Unable to load session. Could not access keyring" when attemptint to log in on Ubuntu Server 20.04

### ISSUE THREAD

**Issue by ObiWanCannobi** [ProtonVPN/linux-cli#276]
**Describe the bug**
This bug was encountered after following instructions for "debian based systems" found here https://protonvpn.com/blog/linux-vpn-cli-beta/

When attempting to log in, protonvpn-cli shows the error ""Unable to load session. Could not access keyring" before asking for login. After entering credentials, it says "attempting to login", makes a new line, then returns to a shell prompt with no login confirmation. Entering incorrect credentials displays the appropriate message before returning to shell. This is only when logging in with the right credentials. 

The same message appears when attempting to use protonvpn-cli after attempting to log in with the correct credentials. 

**To Reproduce**
1. Install protonvpn-cli on an Ubuntu 20.04 server system.
2. Attempt to log in with valid credentials.

**Expected behavior**
A successful login message, followed by the ability to use protonvpn-cli to connect to vpn servers. 

**Error Messages**
"Unable to load session. Could not access keyring"

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 20.04
 - Python Version: 3.8.5
 - ProtonVPN-CLI Version: 3.2.0

**Additional context**

**Comment by calexandru2018** [comment]
Hey @ObiWanCannobi 

This github repo is meant for the community built version, not the official one. Please close this issue and contact our support and provided the necessary logs.

**Comment by ObiWanCannobi** [comment]
@calexandru2018 Noted, will do.
