### ISSUE TITLE
Couldn't reach Proton API.This might happen due to connection issues or network blocks.

### ISSUE THREAD

**Issue by LogunovAV** [ProtonVPN/linux-cli#278]
Moscow, Russia. MGTS.

Proton services are blocked in our country. It works fine on Win 10 Pro (licensed), but this issue happens when I use proton-cli on Linux Mint 19.3
It's a little strange that I need a vpn to enable the vpn... 

Additionally, I have a paid plan and with it I need to move on Win 10 Pro to get it work... Actually, most of the times it's fine, but when I need to work with Linux based OS it's a hell.

**Comment by calexandru2018** [comment]
Hey @LogunovAV 

What version of the CLI are you using ? It is planned for the official CLI to have alternative routing (which will help bypass in countries that restrict our API).

**Comment by LogunovAV** [comment]
@calexandru2018 Thanks for the note, I forget to put technical data. 

I have followed this instruction: 
https://protonvpn.com/support/official-linux-client/

Current version installed after the guidance followance is ProtonVPN CLI v3.2.1

Here is the terminal
![image](https://user-images.githubusercontent.com/71711739/106252697-94862d00-6227-11eb-9b32-ef21a3346fb8.png)
![image](https://user-images.githubusercontent.com/71711739/106252894-d44d1480-6227-11eb-8dc7-deeabf17daef.png)

**Comment by calexandru2018** [comment]
Hey @LogunovAV 

This github repo is meant only for the community version. In regards to what you mention with the official CLI, this is something that we're aware of and will be improving.
