### ISSUE TITLE
sudo protonvpn init returning http 503 error

### ISSUE THREAD

**Issue by Graham1384** [ProtonVPN/linux-cli#281]
I was using proton VPN and it was working so good for about 3 months and then it suddenly disconnected. I purged config and I tried to init but it can't connect to proton VPN API. also I am using 'protonmail.ch' instead 'protonvpn.ch'. searching the link in the browser also returns 503 error. I can't do anything without a VPN.

**Comment by Graham1384** [comment]
![Screenshot from 2021-02-01 11-50-32](https://user-images.githubusercontent.com/62774242/106432271-ba0f7280-6483-11eb-8246-098df394feab.png)

**Comment by Graham1384** [comment]
hopefully, I connected to VPN but the browser still is showing me 503 error. the service is not available but I can connect. what's going on!

**Comment by planetscape** [comment]
Please see:

https://protonstatus.com/incidents/125#update-133

They appear to be working on the issue.

**Comment by bartbutler** [comment]
I should be fixed. Please confirm that you are still having issues connecting.

**Comment by planetscape** [comment]
I am connected now, thank you.

**Comment by Graham1384** [comment]
everything is working now. thanks
