### ISSUE TITLE
[BUG] failure to connect on Fedora 33

### ISSUE THREAD

**Issue by absolutez3** [ProtonVPN/linux-cli#288]
**Describe the bug**
When trying to connect I get the following output:

```
Adding ProtonVPN connection...
Unknown error: org.freedesktop.NetworkManager.Settings.PermissionDenied: uid 1000 has no permission to perform this operation

```

**To Reproduce**
1. Open Terminal
2. Run 'protonvpn-cli c -f'
3. See error 

**Expected behavior**
Connection to the server, creation of interfaces such as proton0.

**Error Messages/Program Output/Log Messages (~/.pvpn-cli/pvpn-cli.log)**
Unknown error: org.freedesktop.NetworkManager.Settings.PermissionDenied: uid 1000 has no permission to perform this operation

**Desktop (please complete the following information):**
 - OS: Fedora 33
 - Python Version: [Python 3.9.1]
 - ProtonVPN-CLI Version: [ProtonVPN CLI v3.3.0 (protonvpn-nm-lib v0.4.1; proton-client v0.3.0)]

**Comment by calexandru2018** [comment]
Please try to update to the latest version:
ProtonVPN CLI v3.3.1
protonvpn-nm-lib v0.4.2

**Comment by absolutez3** [comment]
`sudo dnf list installed --verbose  |grep proton

protonmail-bridge.x86_64                           1.6.3-1                                @@commandline                                  
protonvpn-cli.noarch                               3.3.1-1                                @proton-fedora-33-unstable                     
python3-proton-client.noarch                       0.3.0-1                                @proton-fedora-33-unstable                     
python3-protonvpn-nm-lib.noarch                    0.4.2-1                                @proton-fedora-33-unstable 


sudo nmcli con show
NAME                      UUID                                  TYPE      DEVICE 
default_wifi                snip  wifi      wlp3s0 
ProtonVPN Country#Numbah        8ffcfe3a-6049-44e7-914d-c548dd045562  vpn       --     
pvpn-ipv6leak-protection  9feaaad5-fd30-4dac-a756-f5c23bfc25c6  dummy     --       
Wired connection 1        9d36156f-2ca7-3289-a9ca-2ffa8df860fb  ethernet  --      

protonvpn-cli r
Adding ProtonVPN connection...
Unknown error: org.freedesktop.NetworkManager.Settings.PermissionDenied: uid 1000 has no permission to perform this operation

`

**Comment by absolutez3** [comment]
https://github.com/ProtonVPN/linux-cli/issues/290 with updates
