### ISSUE TITLE
Cannot connect with permanent killswitch enabled

### ISSUE THREAD

**Issue by DasCapschen** [ProtonVPN/linux-cli#3]
Enabling permanent killswitch, then trying to connect leads to the error message

```
An unknown error has occured. Please ensure that you have internet connectivity.
If the issue persists, please contact support.
```

This is kind of counter intuitive, since it requires disabling killswitch, then connecting, then re-enabling killswitch...

**Comment by calexandru2018** [comment]
Hey @DasCapschen 

This is currently being fixed, thank you for the report.

**Comment by calexandru2018** [comment]
Hey @DasCapschen 

This should've been solved with the latest stable update. If the you feel that the issue has been solved, please close this ticket.

**Comment by DasCapschen** [comment]
I can confirm, I no longer see this issue.
