### ISSUE TITLE
Python-systemd required

### ISSUE THREAD

**Issue by ThomasTraineau** [ProtonVPN/linux-cli#34]
When trying to install protonvpn-cli from the AUR (on Artix linux) with yay, I get the error "libsystemd (Dépendances de: protonvpn-gui -> python-protonvpn-nm-lib -> python-systemd)". However, I don't use systemd but openRC. 
I get the same issue with the gui.

**Comment by calexandru2018** [comment]
Hey @ThomasTraineau 

It's explicitly stated on our supported pages that systemd is a requirment: 
- https://protonvpn.com/support/linux-vpn-tool/
- https://protonvpn.com/support/official-linux-vpn-debian/

**Comment by ThomasTraineau** [comment]
Ah indeed. Thanks for the info ! Any hope to get openRC support in the future ?

**Comment by calexandru2018** [comment]
@ThomasTraineau currently there are no plans, as the current implementation heavily relies on systemd to communicate with the OS. It also depends of the level of interoperability of openRC and NetworkManager.

**Comment by eNTi** [comment]
I've just switched to Proton Unlimited just to learn that my distro can't use your app. After using mullvad-vpn and their app sucessfully for quite some time I'm sorely disappointed. I'm also on ArtixLinux + OpenRC and the Mullvad-App works just fine. Just copy their stuff. It's open source too.

**Comment by FrenchGithubUser** [comment]
@eNTi there is a community cli version (also available on the AUR) : https://github.com/Rafficer/linux-cli-community

However it seems like it is not being updated anymore...
