### ISSUE TITLE
custom dns immediately reverts to automatic

### ISSUE THREAD

**Issue by jonz-secops** [ProtonVPN/linux-cli#39]
```protonvpn-cli config --dns custom --ip 192.168.1.1                                   

DNS will be managed by the provided custom IPs: 
192.168.1.18

These changes will apply the next time you connect to VPN.

DNS automatic configuration enabled.
These changes will apply the next time you connect to VPN.
```

ProtonVPN CLI v3.7.2 (protonvpn-nm-lib v3.3.2; proton-client v0.5.1)

This feature is also poorly documented, but I'm thankful for the included example, because the argument explanation in the help was unclear. Also, why not also have an ability to tie domain in as well? I imagine many people who want a custom additional DNS server IP are wanting it for a local or private domain name resolution.

**Comment by calexandru2018** [comment]
Hey @jonz-secops 

A fix has already been issued, it will release with the next CLI update.

**Comment by calexandru2018** [comment]
Already foxed
