### ISSUE TITLE
Accelerator

### ISSUE THREAD

**Issue by Ammako** [ProtonVPN/linux-cli#41]
This is being advertised as being available on *all* ProtonVPN apps for all ProtonVPN users, yet the Linux app doesn't have this functionality yet.

**Comment by calexandru2018** [comment]
The Linux app does have this, it's just that the setting itself is not present for user configuration. Regardless, it's enabled by default and should appear in the next CLI update.

**Comment by Ammako** [comment]
Appreciate the quick reply!
