### ISSUE TITLE
Link in README is broken placeholder

### ISSUE THREAD

**Issue by ivoanjo** [ProtonVPN/linux-cli#5]
Howdy! I was just upgrading from an older protonvpn version and noticed that the following paragraph in the README.md has a broken link:

```
## Installation
Follow our [knowledge base article](to-add) on how to install the CLI on your system.
```

There is no `to-add` is present on the file.

I found the info on your website anyway, so it's not a big thing, but you may want to fix the link :)

**Comment by calexandru2018** [comment]
Hey @ivoanjo 

Thank you for pointing out, this shall be fixed soon. 👍🏻

**Comment by calexandru2018** [comment]
Hey, I'm closing this issue as the new updated has fixed this. 

Thank you for contribution!
