### ISSUE TITLE
What is the future plan for unreasonable dependencies

### ISSUE THREAD

**Issue by matejc** [ProtonVPN/linux-cli#75]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [x] I have searched open and closed issues for duplicates
- [ ] This isn't a feature request
- [ ] This is not a report about my app not working as expected

----------------------------------------

For me, a paying customer of Proton Mail and VPN, latest version of protonvpn-cli is unusable on my workstation. 
Its throwing me the following exception:
```
RuntimeError: Couldn't find acceptable executables for {'systemctl', 'nmcli'}
```

I do not have systemd nor network manager. Some time ago protonvpn-cli tool was working without those dependencies.

What is the future plan to address this issue?

**Comment by calexandru2018** [comment]
Hey @matejc , it would greatly help if you search previous issues before posting a new one, here is the link: https://github.com/ProtonVPN/linux-cli/issues/64#issuecomment-1058224569
