### ISSUE TITLE
Network Error While Trying To Login

### ISSUE THREAD

**Issue by aliazani** [ProtonVPN/linux-cli#78]
Hi there, I was using protonvpn-cli 2.2.11, I mean the old one without GUI but today I'm getting Authentication failed error and when I tried the new version, I couldn't even login and I got Network error.
Logs for errors are like below:

> 2022-06-02 17:14:54,840 — main.py — INFO —do_startup:75 — 
> -------------------------------------------------
> 
> -----------	Initialized protonvpn	-----------
> 
> -------------------------------------------------
> 2022-06-02 17:14:54,842 — main.py — INFO —do_startup:87 — Proton VPN v1.9.0 (protonvpn-nm-lib v3.10.0; proton-client v0.7.1)
> 2022-06-02 17:14:54,846 — main.py — INFO —do_startup:109 — Startup successful
> 2022-06-02 17:14:55,024 — main.py — INFO —do_activate:275 — Window to display <login.LoginView object at 0x7fd13bf4a4c0 (LoginView at 0x5600f911c580)>
> 2022-06-02 17:16:27,574 — login.py — ERROR —__login:92 — Network error
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/site-packages/protonvpn_gui/view_model/login.py", line 53, in __login
>     protonvpn.login(self.__username, self.__password, self.__captcha)
>   File "/usr/lib/python3.10/site-packages/protonvpn_nm_lib/api.py", line 36, in login
>     self._env.api_session.authenticate(username, password, human_verification)
>   File "/usr/lib/python3.10/site-packages/protonvpn_nm_lib/core/session/session.py", line 39, in __call__
>     result = self._func(session, *args, **kwargs)
>   File "/usr/lib/python3.10/site-packages/protonvpn_nm_lib/core/session/session.py", line 390, in authenticate
>     self.__proton_api.authenticate(username, password)
>   File "/usr/lib/python3.10/site-packages/proton/api.py", line 387, in authenticate
>     info_response = self.api_request("/auth/info", payload)
>   File "/usr/lib/python3.10/site-packages/proton/api.py", line 261, in api_request
>     response = self.__try_with_alt_routing(fct, **request_params)
>   File "/usr/lib/python3.10/site-packages/proton/api.py", line 327, in __try_with_alt_routing
>     raise NetworkError("Network error")
> proton.exceptions.NetworkError: Network error
> 2022-06-02 17:19:48,383 — main.py — INFO —on_quit:113 — Quit app
>

**Comment by draekko** [comment]
Could be related to the partial network outage. https://protonstatus.com/

**Comment by aliazani** [comment]
And I'm facing this error while trying to connect via protonvpn-cli:
Unknown error occured. If the issue persists, please contact support.
Sentry is attempting to send 5 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit

logs are like below:

> 2022-06-04 08:01:15,704 — cli.py — INFO — __init__:17 — 
> -------------------------------------------------
> 
> -----------	Initialized protonvpn-cli	-----------
> 
> -------------------------------------------------
> 2022-06-04 08:01:15,705 — cli.py — INFO — __init__:29 — Proton VPN CLI v3.12.0 (protonvpn-nm-lib v3.10.0; proton-client v0.7.1)
> 2022-06-04 08:01:22,150 — cli.py — INFO — __init__:17 — 
> -------------------------------------------------
> 
> -----------	Initialized protonvpn-cli	-----------
> 
> -------------------------------------------------
> 2022-06-04 08:01:22,150 — cli.py — INFO — __init__:29 — Proton VPN CLI v3.12.0 (protonvpn-nm-lib v3.10.0; proton-client v0.7.1)
> 2022-06-04 08:01:22,152 — cli.py — INFO — __init__:64 — CLI command: Namespace(command='login', version=False, help=False, get_logs=False)
> 2022-06-04 08:01:29,320 — cli.py — INFO — __init__:17 — 
> -------------------------------------------------
> 
> -----------	Initialized protonvpn-cli	-----------
> 
> -------------------------------------------------
> 2022-06-04 08:01:29,321 — cli.py — INFO — __init__:29 — Proton VPN CLI v3.12.0 (protonvpn-nm-lib v3.10.0; proton-client v0.7.1)
> 2022-06-04 08:01:29,323 — cli.py — INFO — __init__:64 — CLI command: Namespace(command='login', version=False, help=False, get_logs=False)
> 2022-06-04 08:01:39,348 — cli_wrapper.py — INFO — login:68 — Credentials provided, attempting to login
> 2022-06-04 08:02:42,965 — cli_wrapper.py — ERROR — login:117 — Network error
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/site-packages/protonvpn_cli/cli_wrapper.py", line 73, in login
>     self.protonvpn.login(username, password)
>   File "/usr/lib/python3.10/site-packages/protonvpn_nm_lib/api.py", line 36, in login
>     self._env.api_session.authenticate(username, password, human_verification)
>   File "/usr/lib/python3.10/site-packages/protonvpn_nm_lib/core/session/session.py", line 39, in __call__
>     result = self._func(session, *args, **kwargs)
>   File "/usr/lib/python3.10/site-packages/protonvpn_nm_lib/core/session/session.py", line 390, in authenticate
>     self.__proton_api.authenticate(username, password)
>   File "/usr/lib/python3.10/site-packages/proton/api.py", line 387, in authenticate
>     info_response = self.api_request("/auth/info", payload)
>   File "/usr/lib/python3.10/site-packages/proton/api.py", line 261, in api_request
>     response = self.__try_with_alt_routing(fct, **request_params)
>   File "/usr/lib/python3.10/site-packages/proton/api.py", line 327, in __try_with_alt_routing
>     raise NetworkError("Network error")
> proton.exceptions.NetworkError: Network error

**Comment by aliazani** [comment]
It's related to #10 so I'll close this.
