### ISSUE TITLE
Warning about 'root' user and possible broken permissions

### ISSUE THREAD

**Issue by AngryPhantom** [ProtonVPN/linux-cli#93]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [x] I have searched open and closed issues for duplicates
- [x] This isn't a feature request
- [x] This is not a report about my app not working as expected

----------------------------------------

Hello,

First, I'd really like to thank you for this awesome VPN. It helps a lot reaching some banned websites from other countries (for political reasons etc).
But I have a question. When I install it or upgrade the CLI application afterwards with **sudo** I get a warning like this:

`WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behavior with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv`

As far as I understand it should a system app that creates a connection and stuff and I need **sudo**. Right?
Or do I really have to create this _virtual environment_ instead in order to avoid possible broken permissions in my system?
Anyone with such experience here? And how to create it properly? (I'm sorry, if it's a newbie thing)

Thank you in advance!

**Comment by calexandru2018** [comment]
Hey @AngryPhantom 

Could you paste here the command that you use to launch the CLI please ?

**Comment by AngryPhantom** [comment]
@calexandru2018 

I launch it with:
`sudo protonvpn connect`
or
`sudo protonvpn c -f`

But I got this output in the beginning when I installed proton with:
`sudo pip install protonvpn-cli`

And later when I check for upgrades with:
`sudo pip install protonvpn-cli --upgrade`

Distro: Arch Linux and Void Linux.

**Comment by AngryPhantom** [comment]
P.S. It works but I'm worried with this warning and permissions, etc.

**Comment by calexandru2018** [comment]
So you're running the legacy version of CLI (previous community project) from Pip, which is this one: https://github.com/Rafficer/linux-cli-community. We do not support the use of this package, so if you do, you should do it at your own risk. 

Our official package is based on NetworkManager and thus does not require root permissions. You can find the official meta-package here: https://aur.archlinux.org/packages/protonvpn

**Comment by AngryPhantom** [comment]
@calexandru2018 So you don't have a plain python package anymore? The thing is that I don't use _NetworkManager_, I prefer cli tools or _connman_ as a last resort.

**Comment by AngryPhantom** [comment]
Figured it out. You have also .ovpn configs. That's what I need. Thanks! Cheers.
